kinoapp/urls.py
from django.conf import settings
from django.conf.urls.static import static

from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("movie.urls")),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

movie/urls.py
from django.urls import path
from .views import (
    MovieListView,
    MovieDetailView,
    MovieCreateView,
    MovieUpdateView,
)

app_name = "movie"

urlpatterns = [
    path("", MovieListView.as_view(), name="index"),
    path("movie/<int:pk>/", MovieDetailView.as_view(), name="movie_detail"),
    path("movie/create/", MovieCreateView.as_view(), name="create_movie"),
    path(
        "movie/<int:pk>/update/",
        MovieUpdateView.as_view(),
        name="update_movie",
    ),
]

movie/models.py
from django.db import models
import datetime
from django.core.exceptions import ValidationError
from django.utils.translation import gettext_lazy as _
from sorl.thumbnail import ImageField


class Genre(models.Model):
    name = models.CharField(max_length=50, blank=True, null=True)

    def __str__(self):
        return self.name


def current_year():
    return datetime.date.today().year


def year_validator(value):
    if value < 1888 or value > current_year():
        raise ValidationError(
            _("%(value)s is not a valid year"),
            params={"value": value},
        )


class Movie(models.Model):
    class Meta:
        verbose_name = "Movie"
        verbose_name_plural = "Movies"
        get_latest_by = "created_at"
        ordering = ["-created_at"]

    name = models.CharField(max_length=100)
    year_released = models.IntegerField(
        default=0,
        help_text="YYYY",
        validators=[year_validator],
    )
    description = models.CharField(max_length=2000)
    poster = ImageField(upload_to="movie/posters", null=True, blank=True)
    rating = models.FloatField(
        default=0.0, blank=True, null=True, help_text="0.0 to 10.0"
    )
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    genre = models.ManyToManyField("Genre", related_name="movie")

    def __str__(self):
        return self.name

movie/forms.py
from django.forms import ModelForm
from .models import Movie


class MovieForm(ModelForm):
    class Meta:
        model = Movie
        fields = ("name", "year_released", "description", "poster", "rating")

movie/views.py
from django.db.models import Q
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views.generic import ListView, DetailView, CreateView, UpdateView
from .models import Movie
from .forms import MovieForm


class MovieListView(ListView):
    model = Movie
    template_name = "movie/index.html"
    context_object_name = "movies"
    ordering = ["-created_at"]

    def get_queryset(self):
        queryset = super().get_queryset()
        search_query = self.request.GET.get("search", "")
        if search_query:
            queryset = queryset.filter(
                Q(name__icontains=search_query)
                | Q(description__icontains=search_query)
            )
        ordering = self.request.GET.get("ordering")

        if ordering == "year":
            queryset = queryset.order_by("year_released")
        elif ordering == "genre":
            queryset = queryset.order_by("genre")
        elif ordering == "rating":
            queryset = queryset.order_by("-rating")
        return queryset


class MovieDetailView(DetailView):
    model = Movie
    template_name = "movie/detail.html"
    context_object_name = "movie"


class MovieCreateView(CreateView):
    model = Movie
    template_name = "movie/create_movie.html"
    form_class = MovieForm
    success_url = reverse_lazy("movie:index")


class MovieUpdateView(UpdateView):
    model = Movie
    form_class = MovieForm
    template_name = "movie/create_movie.html"
    success_url = reverse_lazy("movie:index")

movie/templates/movie/base.html
<!-- base.html -->
{% load static %}
{% load thumbnail %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}Welcome to our site{% endblock %}</title>
    <script src='https://cdn.tailwindcss.com'></script>
</head>

<body>
    <nav class='px-6 py-6 flex justify-between items-center border-b border-gray-200'>
        <a href="/" class="text-xl font-semibold">KinoApp</a>
        <div class="space-x-6">
            <a href="{% url 'movie:index' %}" class="text-lg font-semibold hover:text-gray-500">All Movie</a>
            <a href="{% url 'movie:create_movie' %}" class="text-lg font-semibold hover:text-gray-500">Add Movie</a>
        </div>
    </nav>
    <header>
        <!-- Здесь может быть ваш заголовок сайта, меню навигации и т.д. -->
    </header>

    <div class="px-6 py-6">
        {% block content %}
        {% endblock %}
    </div>

    <footer>
        <!-- Здесь может быть футер, контактная информация и т.д. -->
    </footer>
</body>

</html>

movie/templates/movie/create_movie.html
{% extends 'movie/base.html' %}

{% block title %}Create Movie{% endblock %}

{% block content %}
<h1 class="mb-6 text-3xl">Create new movie</h1>
<form method="post" action="." enctype="multipart/form-data">
    {% csrf_token %}
    <div class="space-y-4">{{ form.as_p }}</div>
    {% if form.errors or form.non_field_errors %}
    <div class='mb-3 p-6 bg-red-100 rounded-xl'>
        {% for field in form %}
        {{ firld.errors}}
        {% endfor %}
        {{ form.non_field_errors }}
    </div>
    {% endif %}
    <button class="mt-6 py-4 px-8 text-lg bg-teal-500 hover:bg-teal-700 rounded-xl text-white">Create</button>

</form>
{% endblock %}

movie/templates/movie/detail.html
{% extends 'movie/base.html' %}

{% load thumbnail %}

{% block title %}{{ movie.name }}{% endblock %}

{% block content %}
<div class="grid grid-cols-3 gap-6">
    {% thumbnail movie.poster "200x400" crop="center" as im %}
    <div class="col-span-2"><img src="{{ movie.poster.url }}" width="{{ im.width }}" height="{{ im.height }}"
            alt="movie poster" /></div>
    {% endthumbnail %}
    <div class="col-span-2 p-6 rounded-xl bg-gray-100">
        <h1 class="mb-6 text-3xl ">{{ movie.name }}</h1>
        <p class="text-gray-700">{{ movie.year_released }}</p>

        {% if movie.description %}
        <strong class="text-gray-700">Description:</strong><br>
        <p class="text-gray-500">{{ movie.description }}</p>
        {% endif %}

        <p class="text-gray-700">{{ movie.rating }}</p>
    </div>

</div>
<a href="{% url 'movie:update_movie' movie.id %}"
    class="inline-block mt-6 px-6 py-3 text-lg font-semibold bg-teal-500 text-white rounded-xl">Update</a>

{% endblock %}

movie/templates/movie/index.html
<!-- index.html -->
{% extends "movie/base.html" %}
{% load thumbnail %}

{% block title %}All Films{% endblock %}

{% block content %}
<form method="get">
    <select name="ordering">
        <option value="year">by year</option>
        <option value="genre">by genre</option>
        <option value="rating">by rating</option>
    </select>
    <input type="submit" value="Sort now">
</form>
<form method='get' action="{% url 'movie:index' %}">
    <input name="search" class="w-full py-4 px-6 border rounded-xl" type="text" value="{{ query }}"
        placeholder="Find a film ...">
    <button class="mt-2 py-4 px-8 text-lg bg-teal-500 text-white rounded-xl">Search</button>
</form>




<div class="col-span-3">
    <div class="grid grid-cols-3 gap-3">

        {% if movies %}
        {% for movie in movies %}
        <div>
            <a href="{% url 'movie:movie_detail' movie.id %}">
                <h2 class="text-3xl">{{ movie.name }}</h2>

                {{ movie.description }}
                {% thumbnail movie.poster "180x300" crop="center" as im %}
                <div>
                    <img src="{{ im.url }}" width="{{ im.width }}" height="{{ im.height }}" alt="movie poster" />
                </div>
                {% endthumbnail %}
                <div class="p-6 bg-white rounded-b-xl">
                    <p class="text-xl">Year of Release: {{ movie.year_released }}</p>
                    <p class="text-gray-500">Rating: {{ movie.rating }}</p>
                </div>
                <!--<img class="card-img-top" src="{{ movie.poster.url }}" alt="movie poster" />-->

            </a>
        </div>
        {% endfor %}
        {% else %}
        <p>No movies found.</p>
        {% endif %}

    </div>

</div>
{% endblock %}